In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [3]:
df = pd.read_csv("/content/EDA (1).csv")

df.head()

,Brand,Model,Price,Rating_Count,RAM_GB,ROM_GB,Color,Display_cm,Screen_Type,Panel_Type,Rear_Camera_MP,Battery_mAh,Display,Camera,Processor
0,realme,"P4 Power 5G (TransSilver, 128 GB)",28999,5913,8,128,TransSilver,17.27,OLED,Other,50.0,10001,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,Dimensity 7400 Ultra Processor
1,vivo,"T5 Pro 5G (Glacier Blue, 128 GB)",32999,5936,8,128,Glacier Blue,17.35,OLED,Other,50.0,9020,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,Snapdragon 7s Gen 4 Processor
2,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",12999,4434,4,128,Limelight Green,17.12,Other,Other,50.0,6000,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor
3,Ai+,"Pulse 2 (Purple, 64 GB)",8999,4359,4,64,Purple,17.13,Other,Other,50.0,6000,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,T7250 Processor
4,vivo,"X200T (Stellar Black, 256 GB)",59999,5612,12,256,Stellar Black,16.94,OLED,Other,50.0,6200,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           730 non-null    object
 1   Model           730 non-null    object
 2   Price           730 non-null    int64
 3   Rating_Count    730 non-null    int64
 4   RAM_GB          730 non-null    int64
 5   ROM_GB          730 non-null    int64
 6   Color           730 non-null    object
 7   Display_cm      730 non-null    float64
 8   Screen_Type     730 non-null    object
 9   Panel_Type      730 non-null    object
 10  Rear_Camera_MP  730 non-null    float64
 11  Battery_mAh     730 non-null    int64
 12  Display         730 non-null    object
 13  Camera          730 non-null    object
 14  Processor       730 non-null    object
dtypes: float64(2), int64(5), object(8)
memory usage: 85.7+ KB

In [5]:
df.isnull().sum()

Brand             0
Model             0
Price             0
Rating_Count      0
RAM_GB            0
ROM_GB            0
Color             0
Display_cm        0
Screen_Type       0
Panel_Type        0
Rear_Camera_MP    0
Battery_mAh       0
Display           0
Camera            0
Processor         0
dtype: int64

In [6]:
X = df.drop(columns=["Price", "Processor", "Display", "Camera"])

y = df["Price"]

In [7]:
X = pd.get_dummies(
    X,
    columns=[
        "Brand",
        "Color",
        "Screen_Type",
        "Panel_Type"
    ],
    drop_first=True
)

In [8]:
X.head()

,Model,Rating_Count,RAM_GB,ROM_GB,Display_cm,Rear_Camera_MP,Battery_mAh,Brand_Ai+,Brand_Alcatel,Brand_Coolpad,...,Color_Victory Gold,Color_Victory Green,Color_Viva Magenta,Color_Vivid Mint,Color_Waterfall Blue,Color_White,Color_White Knight,Color_Yellow,Color_stellar blue/ steller blue,Screen_Type_Other
0,"P4 Power 5G (TransSilver, 128 GB)",5913,8,128,17.27,50.0,10001,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,"T5 Pro 5G (Glacier Blue, 128 GB)",5936,8,128,17.35,50.0,9020,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,"Galaxy F70e 5G (Limelight Green, 128 GB)",4434,4,128,17.12,50.0,6000,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,"Pulse 2 (Purple, 64 GB)",4359,4,64,17.13,50.0,6000,True,False,False,...,False,False,False,False,False,False,False,False,False,True
4,"X200T (Stellar Black, 256 GB)",5612,12,256,16.94,50.0,6200,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
X = df.drop(columns=[
    "Price",
    "Processor",
    "Display",
    "Camera",
    "Color"
])

In [10]:
X = pd.get_dummies(
    X,
    columns=[
        "Brand",
        "Screen_Type",
        "Panel_Type"
    ],
    drop_first=True
)

In [11]:
X = df.drop(columns=[
    "Price",
    "Model",
    "Processor",
    "Display",
    "Camera",
    "Color"
])

y = df["Price"]

In [12]:
X.shape

(730, 9)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [14]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Nothing'

In [15]:
X = pd.get_dummies(
    X,
    columns=["Brand", "Screen_Type", "Panel_Type"],
    drop_first=True,
    dtype=int
)

In [16]:
print(X.select_dtypes(include="object").columns)

Index([], dtype='object')

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [18]:
print(X_train.dtypes)

Rating_Count           int64
RAM_GB                 int64
ROM_GB                 int64
Display_cm           float64
Rear_Camera_MP       float64
Battery_mAh            int64
Brand_Ai+              int64
Brand_Alcatel          int64
Brand_Coolpad          int64
Brand_Google           int64
Brand_HMD              int64
Brand_IQOO             int64
Brand_Infinix          int64
Brand_LAVA             int64
Brand_Lenovo           int64
Brand_MOTOROLA         int64
Brand_Mi               int64
Brand_Motorola         int64
Brand_Nothing          int64
Brand_OPPO             int64
Brand_OnePlus          int64
Brand_POCO             int64
Brand_REDMI            int64
Brand_Redmi            int64
Brand_SIAVANTAGE       int64
Brand_Samsung          int64
Brand_Tecno            int64
Brand_Vivo             int64
Brand_XOME             int64
Brand_Xiaomi           int64
Brand_itel             int64
Brand_realme           int64
Brand_vivo             int64
Screen_Type_Other      int64
dtype: object

In [19]:
X = df.drop(columns=[
    "Price",
    "Model",
    "Processor",
    "Display",
    "Camera",
    "Color"
])

y = df["Price"]

In [20]:
X = pd.get_dummies(
    X,
    columns=["Brand", "Screen_Type", "Panel_Type"],
    drop_first=True,
    dtype=int
)

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [22]:
print(X_train.shape)
print(X_train.dtypes.value_counts())

(584, 34)
int64      32
float64     2
Name: count, dtype: int64

In [23]:
model = LinearRegression()
model.fit(X_train.values, y_train.values)

LinearRegression()

In [24]:
y_pred = model.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

print("R² Score :", r2_score(y_test, y_pred))
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))

R² Score : 0.7001841884626767
MAE : 7828.82477541259
MSE : 130733404.1598557
RMSE : 11433.870917578863

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [25]:
df["Brand"] = df["Brand"].str.upper()

In [ ]:
df["Brand"].unique()

array(['REALME', 'VIVO', 'SAMSUNG', 'AI+', 'XOME', 'POCO', 'IQOO',
       'MOTOROLA', 'REDMI', 'OPPO', 'INFINIX', 'HMD', 'NOTHING', 'LAVA',
       'ONEPLUS', 'GOOGLE', 'ALCATEL', 'TECNO', 'ITEL', 'ACER', 'COOLPAD',
       'MI', 'XIAOMI', 'SIAVANTAGE', 'LENOVO'], dtype=object)

In [26]:
X = df.drop(columns=[
    "Price",
    "Model",
    "Processor",
    "Display",
    "Camera",
    "Color"
])

y = df["Price"]

In [27]:
X = pd.get_dummies(
    X,
    columns=["Brand", "Screen_Type", "Panel_Type"],
    drop_first=True,
    dtype=int
)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [30]:
y_pred = model.predict(X_test)

In [31]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

print("R²:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R²: 0.7017597637032547
MAE: 7797.648241528361
RMSE: 11403.78802438946

In [32]:
import pickle

In [33]:
with open("price_model.pkl", "wb") as f:
    pickle.dump(model, f)

In [34]:
with open("feature_columns.pkl", "wb") as f:
    pickle.dump(X.columns.tolist(), f)

In [35]:
df.to_csv("model.csv", index=False)

In [36]:
from google.colab import files

files.download("price_model.pkl")
files.download("feature_columns.pkl")
files.download("model.csv")